### ISSUE TITLE
Remove stick to Windows for games

### ISSUE THREAD

**Issue by ogaskell** [lmanul/whylinuxisbetter#32]
With software such as steam proton Linux game performance is equal to Windows now, so the Games entry under when to stick to Windows should be removed.

**Comment by lmanul** [comment]
Hmm, I'm not sure I agree with that. Yes Proton makes things easier, and things have definitely been getting much better, but note that I specifically mention "hardcore gamers" here, not people who have already converted to Linux and want to do some gaming on the side. I mean people who probably tune their PC for the sole purpose of gaming, and do not compromise on performance. If my best friend was a "hardcore gamer" in that way, I would recommend that he or she stick to Windows, because Linux support, while getting better quickly, can still be a bit of a pain or hit-or-miss depending on the game -- and these gamers usually want to play the newest games.
